// <auto-generated />
namespace PoELadder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class removed_models_aka_deleted_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removed_models_aka_deleted_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202002062156044_removed_models_aka_deleted_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
