// <auto-generated />
namespace PoELadder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Edited_the_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Edited_the_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202002062237006_Edited_the_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
