// <auto-generated />
namespace PoELadder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class added_standard_player_entries1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_standard_player_entries1));
        
        string IMigrationMetadata.Id
        {
            get { return "202005181609220_added_standard_player_entries1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
