// <auto-generated />
namespace PoELadder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class added_db_sets_for_depth_and_challanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_db_sets_for_depth_and_challanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202002032203190_added_db_sets_for_depth_and_challanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
